name: Blog Automation

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  collect-and-process:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install feedparser requests beautifulsoup4
    
    - name: Run blog automation
      run: python blog_automation.py
    
    - name: Show results
      run: |
        if [ -f collected_posts.json ]; then
          echo "=== 수집 완료! ==="
          echo "파일 크기: $(ls -lh collected_posts.json | awk '{print $5}')"
          echo "=== 내용 미리보기 ==="
          head -c 500 collected_posts.json
        else
          echo "❌ collected_posts.json 파일이 생성되지 않았습니다."
        fi
    
    # 이것만으로도 충분합니다!
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: collected-posts
        path: collected_posts.json
        retention-days: 30
